apiVersion: v2
name: bkms-server
description: A Helm chart for bkms server
type: application
version: 1.0.0-alpha.30
appVersion: v1.0.0-alpha.30
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.13.3
